path:
  # --- shared
  calendar_path: E:\OneDrive\Data\Calendar\cne_calendar.csv
  root_dir: E:\OneDrive\Data\tushare
  daily_data_root_dir: E:\OneDrive\Data\tushare\by_date
  db_struct_path: E:\OneDrive\Data\tushare\db_struct.yaml
  alternative_dir: E:\OneDrive\Data\Alternative
  market_index_path: E:\OneDrive\Data\Market\index.xlsx
  by_instru_pos_dir: E:\OneDrive\Data\tushare\by_instrument\position
  by_instru_pre_dir: E:\OneDrive\Data\tushare\by_instrument\preprocess
  by_instru_min_dir: E:\OneDrive\Data\tushare\by_instrument\minute_bar
  instru_info_path: E:\OneDrive\Data\tushare\instruments.csv

  # --- project
  project_root_dir: E:\Data\Projects\CTA_V7

universe:
  AU.SHF:
    sectorL0: C
    sectorL1: AUG
  AG.SHF:
    sectorL0: C
    sectorL1: AUG
  CU.SHF:
    sectorL0: C
    sectorL1: MTL
  AL.SHF:
    sectorL0: C
    sectorL1: MTL
  PB.SHF:
    sectorL0: C
    sectorL1: MTL
  ZN.SHF:
    sectorL0: C
    sectorL1: MTL
  NI.SHF:
    sectorL0: C
    sectorL1: MTL
  SN.SHF:
    sectorL0: C
    sectorL1: MTL
  SS.SHF:
    sectorL0: C
    sectorL1: MTL
  AO.SHF:
    sectorL0: C
    sectorL1: MTL
  A.DCE:
    sectorL0: C
    sectorL1: OIL
  B.DCE:
    sectorL0: C
    sectorL1: OIL
  M.DCE:
    sectorL0: C
    sectorL1: OIL
  P.DCE:
    sectorL0: C
    sectorL1: OIL
  Y.DCE:
    sectorL0: C
    sectorL1: OIL
  OI.ZCE:
    sectorL0: C
    sectorL1: OIL
  RM.ZCE:
    sectorL0: C
    sectorL1: OIL
  RU.SHF:
    sectorL0: C
    sectorL1: CHM
  BR.SHF:
    sectorL0: C
    sectorL1: CHM
  BU.SHF:
    sectorL0: C
    sectorL1: CHM
  FU.SHF:
    sectorL0: C
    sectorL1: CHM
  L.DCE:
    sectorL0: C
    sectorL1: CHM
  V.DCE:
    sectorL0: C
    sectorL1: CHM
  EB.DCE:
    sectorL0: C
    sectorL1: CHM
  EG.DCE:
    sectorL0: C
    sectorL1: CHM
  PP.DCE:
    sectorL0: C
    sectorL1: CHM
  PG.DCE:
    sectorL0: C
    sectorL1: CHM
  MA.ZCE:
    sectorL0: C
    sectorL1: CHM
  TA.ZCE:
    sectorL0: C
    sectorL1: CHM
  RB.SHF:
    sectorL0: C
    sectorL1: BLK
  HC.SHF:
    sectorL0: C
    sectorL1: BLK
  I.DCE:
    sectorL0: C
    sectorL1: BLK
  J.DCE:
    sectorL0: C
    sectorL1: BLK
  JM.DCE:
    sectorL0: C
    sectorL1: BLK
  SF.ZCE:
    sectorL0: C
    sectorL1: BLK
  SM.ZCE:
    sectorL0: C
    sectorL1: BLK
  ZC.ZCE:
    sectorL0: C
    sectorL1: BLK
  FG.ZCE:
    sectorL0: C
    sectorL1: BLK
  SA.ZCE:
    sectorL0: C
    sectorL1: BLK
  UR.ZCE:
    sectorL0: C
    sectorL1: BLK
  AP.ZCE:
    sectorL0: C
    sectorL1: AGR
  CF.ZCE:
    sectorL0: C
    sectorL1: AGR
  SR.ZCE:
    sectorL0: C
    sectorL1: AGR
  CY.ZCE:
    sectorL0: C
    sectorL1: AGR
  CJ.ZCE:
    sectorL0: C
    sectorL1: AGR
  PK.ZCE:
    sectorL0: C
    sectorL1: AGR
  JD.DCE:
    sectorL0: C
    sectorL1: AGR
  LH.DCE:
    sectorL0: C
    sectorL1: AGR
  C.DCE:
    sectorL0: C
    sectorL1: AGR
  CS.DCE:
    sectorL0: C
    sectorL1: AGR

available:
  win: 10
  amount_threshold: 100000.00
  win_vol: 60
  win_vol_min: 20

icov:
  win: 60

css:
  vma_win: 5
  vma_threshold: 0.0175
  vma_wgt: 0.2
  sev_win: 20

mkt:
  equity: 881001.WI
  commodity: NH0100.NHF

# ------- const -------
CONST:
  INIT_CASH: 100_000_000
  COST_RATE: 0.0003
  LAG: 1
